"""The data behind `python seed.py`: restriction tags, known ingredients and substitutes.

Kept apart from seed.py (which talks to the database) so the data can be
checked by tests without a database, and so seed.py stays short.

How to read INGREDIENTS: each key is an ingredient name, each value the list
of restriction tags it carries. An empty list means "known and safe for every
tag"; it still needs a row so the matcher recognizes it instead of reporting
"unrecognized". Matching is whole-word and longest-match-wins (see
app/normalize.py), so a specific entry only needs its own line when a broader
word already in the dictionary would give the wrong answer. That is why
"almond flour" and "cream of tartar" exist: without them, "flour" would flag
gluten and "cream" would flag dairy.
"""

TAGS = [
    "gluten", "dairy", "lactose", "egg", "honey", "meat",
    "fish", "shellfish", "tree_nuts", "peanuts", "soy",
    "sesame", "mustard", "sulphites",
]

# Diet presets: UI shortcut buttons that switch on several restriction tags at once.
# Vegan and vegetarian include shellfish, so shrimp is not treated as "fine".
DIET_PRESETS = {
    "vegan": ["meat", "fish", "shellfish", "dairy", "egg", "honey"],
    "vegetarian": ["meat", "fish", "shellfish"],
    "gluten_free": ["gluten"],
    "lactose_free": ["lactose"],
}

INGREDIENTS = {
    # grains / gluten
    "flour": ["gluten"],
    "wheat flour": ["gluten"],
    "plain flour": ["gluten"],
    "self raising flour": ["gluten"],
    "bread": ["gluten"],
    "breadcrumbs": ["gluten"],
    "panko": ["gluten"],
    "pasta": ["gluten"],
    "spaghetti": ["gluten"],
    "penne": ["gluten"],
    "macaroni": ["gluten"],
    "fusilli": ["gluten"],
    "linguine": ["gluten"],
    "tagliatelle": ["gluten"],
    "lasagne": ["gluten"],
    "lasagna": ["gluten"],
    "noodles": ["gluten"],
    "egg noodles": ["gluten", "egg"],
    "couscous": ["gluten"],
    "bulgur": ["gluten"],
    "semolina": ["gluten"],
    "barley": ["gluten"],
    "rye": ["gluten"],
    "pastry": ["gluten"],
    "puff pastry": ["gluten"],
    "pie crust": ["gluten"],
    "tortilla": ["gluten"],
    "pita": ["gluten"],
    "bun": ["gluten"],
    "baguette": ["gluten"],
    "cracker": ["gluten"],
    "soy sauce": ["soy", "gluten"],
    "worcestershire sauce": ["fish"],
    "rice": [],
    "brown rice": [],
    "rice noodles": [],
    "quinoa": [],
    "oats": [],
    "polenta": [],
    "cornstarch": [],
    "corn": [],
    "cornmeal": [],

    # eggs
    "egg": ["egg"],
    "quail egg": ["egg"],
    "mayonnaise": ["egg"],
    "meringue": ["egg"],

    # dairy
    "butter": ["dairy", "lactose"],
    "milk": ["dairy", "lactose"],
    "buttermilk": ["dairy", "lactose"],
    "cheese": ["dairy", "lactose"],
    "cheddar": ["dairy", "lactose"],
    "mozzarella": ["dairy", "lactose"],
    "parmesan": ["dairy", "lactose"],
    "pecorino": ["dairy", "lactose"],
    "feta": ["dairy", "lactose"],
    "ricotta": ["dairy", "lactose"],
    "mascarpone": ["dairy", "lactose"],
    "brie": ["dairy", "lactose"],
    "gouda": ["dairy", "lactose"],
    "halloumi": ["dairy", "lactose"],
    "cream": ["dairy", "lactose"],
    "cream cheese": ["dairy", "lactose"],
    "heavy cream": ["dairy", "lactose"],
    "whipping cream": ["dairy", "lactose"],
    "sour cream": ["dairy", "lactose"],
    "yogurt": ["dairy", "lactose"],
    "yoghurt": ["dairy", "lactose"],
    "condensed milk": ["dairy", "lactose"],
    "evaporated milk": ["dairy", "lactose"],
    "milk chocolate": ["dairy", "lactose"],
    "custard": ["dairy", "lactose", "egg"],
    "ice cream": ["dairy", "lactose"],

    # sweeteners
    "honey": ["honey"],
    "sugar": [],
    "brown sugar": [],
    "icing sugar": [],
    "powdered sugar": [],
    "maple syrup": [],
    "vanilla extract": [],
    "vanilla": [],

    # meat / cured meat
    "chicken": ["meat"],
    "beef": ["meat"],
    "ground beef": ["meat"],
    "mince": ["meat"],
    "pork": ["meat"],
    "bacon": ["meat"],
    "pancetta": ["meat"],
    "prosciutto": ["meat"],
    "guanciale": ["meat"],
    "chorizo": ["meat"],
    "sausage": ["meat"],
    "salami": ["meat"],
    "ham": ["meat"],
    "turkey": ["meat"],
    "duck": ["meat"],
    "lamb": ["meat"],
    "veal": ["meat"],
    "venison": ["meat"],
    "chicken stock": ["meat"],
    "beef stock": ["meat"],
    "chicken broth": ["meat"],
    "beef broth": ["meat"],
    "gelatin": ["meat"],

    # fish / shellfish
    "salmon": ["fish"],
    "tuna": ["fish"],
    "cod": ["fish"],
    "haddock": ["fish"],
    "halibut": ["fish"],
    "mackerel": ["fish"],
    "sardine": ["fish"],
    "trout": ["fish"],
    "anchovy": ["fish"],
    "sea bass": ["fish"],
    "fish sauce": ["fish"],
    "fish stock": ["fish"],
    "shrimp": ["shellfish"],
    "prawn": ["shellfish"],
    "crab": ["shellfish"],
    "lobster": ["shellfish"],
    "mussels": ["shellfish"],
    "clams": ["shellfish"],
    "oyster": ["shellfish"],
    "scallop": ["shellfish"],
    "squid": ["shellfish"],
    "calamari": ["shellfish"],

    # nuts & seeds
    "almond": ["tree_nuts"],
    "walnut": ["tree_nuts"],
    "cashew": ["tree_nuts"],
    "hazelnut": ["tree_nuts"],
    "pistachio": ["tree_nuts"],
    "pecan": ["tree_nuts"],
    "macadamia": ["tree_nuts"],
    "brazil nut": ["tree_nuts"],
    "pine nut": ["tree_nuts"],
    "peanut": ["peanuts"],
    "peanut butter": ["peanuts"],
    "sesame oil": ["sesame"],
    "sesame seeds": ["sesame"],
    "tahini": ["sesame"],

    # soy / legumes
    "tofu": ["soy"],
    "soy milk": ["soy"],
    "tempeh": ["soy"],
    "edamame": ["soy"],
    "miso": ["soy"],
    "chickpeas": [],
    "lentils": [],
    "black beans": [],
    "kidney beans": [],
    "cannellini beans": [],
    "split peas": [],

    # condiments / pantry
    "mustard": ["mustard"],
    "vinegar": [],
    "balsamic vinegar": [],
    "red wine vinegar": [],
    "apple cider vinegar": [],
    "rice vinegar": [],
    "olive oil": [],
    "vegetable oil": [],
    "sunflower oil": [],
    "canola oil": [],
    "coconut oil": [],
    "coconut milk": [],
    "coconut cream": [],
    "wine": ["sulphites"],
    "white wine": ["sulphites"],
    "red wine": ["sulphites"],
    "dried apricot": ["sulphites"],
    "raisins": ["sulphites"],
    "ketchup": [],
    "tomato sauce": [],
    "tomato paste": [],
    "passata": [],
    "stock": [],
    "vegetable stock": [],
    "vegetable broth": [],
    "water": [],

    # produce & other staples (safe by default)
    "garlic": [],
    "onion": [],
    "spring onion": [],
    "shallot": [],
    "leek": [],
    "tomato": [],
    "potato": [],
    "sweet potato": [],
    "carrot": [],
    "celery": [],
    "bell pepper": [],
    "chili pepper": [],
    "chilli": [],
    "spinach": [],
    "kale": [],
    "lettuce": [],
    "cabbage": [],
    "cucumber": [],
    "zucchini": [],
    "courgette": [],
    "broccoli": [],
    "cauliflower": [],
    "mushroom": [],
    "eggplant": [],
    "aubergine": [],
    "avocado": [],
    "peas": [],
    "green beans": [],
    "sweetcorn": [],
    "apple": [],
    "banana": [],
    "lemon": [],
    "lime": [],
    "orange": [],
    "mango": [],
    "pineapple": [],
    "ginger": [],
    "salt": [],
    "black pepper": [],
    "paprika": [],
    "cumin": [],
    "coriander": [],
    "cilantro": [],
    "oregano": [],
    "basil": [],
    "thyme": [],
    "rosemary": [],
    "parsley": [],
    "mint": [],
    "dill": [],
    "chives": [],
    "bay leaf": [],
    "cinnamon": [],
    "nutmeg": [],
    "turmeric": [],
    "curry powder": [],
    "chili flakes": [],
    "cayenne": [],
    "cocoa powder": [],
    "dark chocolate": [],
    "baking powder": [],
    "baking soda": [],
    "yeast": [],

    # added: gluten-free look-alikes. Without these, a plain 'flour' / 'pasta' / 'noodle' match would wrongly flag them ('gluten-free X' phrases are handled by the qualifier rule instead)
    "almond flour": ["tree_nuts"],
    "coconut flour": [],
    "rice flour": [],
    "corn flour": [],
    "chickpea flour": [],
    "oat flour": [],
    "buckwheat flour": [],
    "cassava flour": [],
    "tapioca flour": [],
    "rice pasta": [],
    "rice spaghetti": [],
    "corn pasta": [],
    "lentil pasta": [],
    "chickpea pasta": [],
    "rice cracker": [],
    "corn tortilla": [],
    "rice paper": [],
    "shirataki noodle": [],
    "glass noodle": [],
    "cellophane noodle": [],
    "coconut aminos": [],
    "tapioca starch": [],
    "potato starch": [],
    "arrowroot": [],
    "xanthan gum": [],
    "psyllium husk": [],
    "buckwheat": [],
    "millet": [],
    "amaranth": [],
    "sorghum": [],
    "teff": [],

    # added: gluten
    "wheat": ["gluten"],
    "spelt": ["gluten"],
    "kamut": ["gluten"],
    "farro": ["gluten"],
    "freekeh": ["gluten"],
    "seitan": ["gluten"],
    "malt": ["gluten"],
    "malt vinegar": ["gluten"],
    "beer": ["gluten"],
    "gnocchi": ["gluten"],
    "orzo": ["gluten"],
    "rigatoni": ["gluten"],
    "farfalle": ["gluten"],
    "fettuccine": ["gluten"],
    "pappardelle": ["gluten"],
    "ravioli": ["gluten"],
    "tortellini": ["gluten"],
    "cannelloni": ["gluten"],
    "ramen": ["gluten"],
    "udon": ["gluten"],
    "dough": ["gluten"],
    "pizza dough": ["gluten"],
    "pizza base": ["gluten"],
    "bagel": ["gluten"],
    "naan": ["gluten"],
    "chapati": ["gluten"],
    "roti": ["gluten"],
    "flatbread": ["gluten"],
    "ciabatta": ["gluten"],
    "sourdough": ["gluten"],
    "pretzel": ["gluten"],
    "biscuit": ["gluten"],
    "crouton": ["gluten"],
    "breadstick": ["gluten"],
    "english muffin": ["gluten"],
    "filo": ["gluten"],
    "phyllo": ["gluten"],
    "wonton wrapper": ["gluten"],
    "dumpling wrapper": ["gluten"],
    "croissant": ["gluten", "dairy", "lactose"],
    "brioche": ["gluten", "egg", "dairy", "lactose"],

    # added: eggs
    "eggnog": ["egg", "dairy", "lactose"],
    "mayo": ["egg"],
    "aioli": ["egg"],
    "hollandaise": ["egg", "dairy", "lactose"],
    "marshmallow": ["meat"],
    "flax egg": [],
    "chia egg": [],
    "egg replacer": [],
    "aquafaba": [],

    # added: dairy
    "whey": ["dairy", "lactose"],
    "casein": ["dairy"],
    "ghee": ["dairy"],
    "paneer": ["dairy", "lactose"],
    "labneh": ["dairy", "lactose"],
    "skyr": ["dairy", "lactose"],
    "kefir": ["dairy", "lactose"],
    "quark": ["dairy", "lactose"],
    "creme fraiche": ["dairy", "lactose"],
    "half and half": ["dairy", "lactose"],
    "dulce de leche": ["dairy", "lactose"],
    "gelato": ["dairy", "lactose"],
    "buttercream": ["dairy", "lactose"],
    "white chocolate": ["dairy", "lactose"],
    "gorgonzola": ["dairy", "lactose"],
    "stilton": ["dairy", "lactose"],
    "camembert": ["dairy", "lactose"],
    "emmental": ["dairy", "lactose"],
    "gruyere": ["dairy", "lactose"],
    "provolone": ["dairy", "lactose"],
    "manchego": ["dairy", "lactose"],
    "asiago": ["dairy", "lactose"],
    "romano": ["dairy", "lactose"],
    "fontina": ["dairy", "lactose"],
    "cotija": ["dairy", "lactose"],
    "queso fresco": ["dairy", "lactose"],
    "burrata": ["dairy", "lactose"],
    "taleggio": ["dairy", "lactose"],
    "monterey jack": ["dairy", "lactose"],
    "pepper jack": ["dairy", "lactose"],
    "cream of tartar": [],
    "cocoa butter": [],
    "butter bean": [],
    "apple butter": [],
    "coconut butter": [],
    "cream of coconut": [],
    "coconut yogurt": [],
    "coconut sugar": [],
    "coconut water": [],
    "desiccated coconut": [],
    "coconut flake": [],
    "coconut": [],
    "vegan margarine": [],
    "oat milk": [],
    "rice milk": [],
    "almond milk": ["tree_nuts"],
    "cashew milk": ["tree_nuts"],
    "soya milk": ["soy"],
    "soy yogurt": ["soy"],

    # added: meat
    "meat": ["meat"],
    "steak": ["meat"],
    "ribeye": ["meat"],
    "sirloin": ["meat"],
    "brisket": ["meat"],
    "short rib": ["meat"],
    "oxtail": ["meat"],
    "mutton": ["meat"],
    "goat": ["meat"],
    "rabbit": ["meat"],
    "bison": ["meat"],
    "liver": ["meat"],
    "meatball": ["meat"],
    "hot dog": ["meat"],
    "frankfurter": ["meat"],
    "bratwurst": ["meat"],
    "pepperoni": ["meat"],
    "mortadella": ["meat"],
    "jerky": ["meat"],
    "lard": ["meat"],
    "suet": ["meat"],
    "tallow": ["meat"],
    "bone broth": ["meat"],
    "gelatine": ["meat"],

    # added: fish & shellfish
    "fish": ["fish"],
    "tilapia": ["fish"],
    "snapper": ["fish"],
    "swordfish": ["fish"],
    "mahi mahi": ["fish"],
    "pollock": ["fish"],
    "herring": ["fish"],
    "eel": ["fish"],
    "caviar": ["fish"],
    "roe": ["fish"],
    "bonito": ["fish"],
    "dashi": ["fish"],
    "surimi": ["fish"],
    "shellfish": ["shellfish"],
    "crayfish": ["shellfish"],
    "langoustine": ["shellfish"],
    "cuttlefish": ["shellfish"],
    "octopus": ["shellfish"],
    "seafood": ["fish", "shellfish"],

    # added: nuts, seeds, sesame, soy, mustard, sulphites, honey
    "chestnut": ["tree_nuts"],
    "water chestnut": [],
    "marzipan": ["tree_nuts"],
    "praline": ["tree_nuts"],
    "nougat": ["tree_nuts"],
    "frangipane": ["tree_nuts"],
    "almond butter": ["tree_nuts"],
    "cashew butter": ["tree_nuts"],
    "nutella": ["tree_nuts", "dairy", "lactose"],
    "pesto": ["tree_nuts", "dairy", "lactose"],
    "groundnut": ["peanuts"],
    "sunflower seed": [],
    "sunflower seed butter": [],
    "pumpkin seed": [],
    "chia seed": [],
    "flaxseed": [],
    "poppy seed": [],
    "hemp seed": [],
    "sesame": ["sesame"],
    "halva": ["sesame"],
    "hummus": ["sesame"],
    "za'atar": ["sesame"],
    "dijon": ["mustard"],
    "soya": ["soy"],
    "soy bean": ["soy"],
    "soybean": ["soy"],
    "soy flour": ["soy"],
    "soy protein": ["soy"],
    "natto": ["soy"],
    "bean curd": ["soy"],
    "sultana": ["sulphites"],
    "sherry": ["sulphites"],
    "marsala": ["sulphites"],
    "vermouth": ["sulphites"],
    "champagne": ["sulphites"],
    "prosecco": ["sulphites"],
    "brandy": ["sulphites"],
    "cognac": ["sulphites"],
    "port wine": ["sulphites"],
    "rice wine": ["sulphites"],
    "wine vinegar": [],
    "white wine vinegar": [],
    "rice wine vinegar": [],
    "sherry vinegar": [],
    "honeycomb": ["honey"],
    "agave": [],
    "golden syrup": [],
    "molasses": [],
    "corn syrup": [],
    "date syrup": [],
    "treacle": [],
    "stevia": [],

    # added: vegetables
    "asparagus": [],
    "artichoke": [],
    "beetroot": [],
    "beet": [],
    "radish": [],
    "turnip": [],
    "parsnip": [],
    "swede": [],
    "pumpkin": [],
    "squash": [],
    "butternut squash": [],
    "fennel": [],
    "okra": [],
    "brussels sprout": [],
    "bok choy": [],
    "pak choi": [],
    "chard": [],
    "rocket": [],
    "arugula": [],
    "watercress": [],
    "endive": [],
    "radicchio": [],
    "romaine": [],
    "collard green": [],
    "scallion": [],
    "jalapeno": [],
    "serrano": [],
    "poblano": [],
    "capsicum": [],
    "pepper": [],
    "peppercorn": [],
    "olive": [],
    "caper": [],
    "pickle": [],
    "gherkin": [],
    "sauerkraut": [],
    "kimchi": [],
    "bean sprout": [],
    "bean": [],
    "broad bean": [],
    "fava bean": [],
    "lima bean": [],
    "pinto bean": [],
    "navy bean": [],
    "borlotti bean": [],
    "haricot bean": [],
    "baked bean": [],
    "mung bean": [],
    "kohlrabi": [],
    "daikon": [],
    "jicama": [],
    "yam": [],
    "cassava": [],
    "plantain": [],
    "sun dried tomato": [],
    "tomatillo": [],
    "shiitake": [],
    "portobello": [],
    "oyster mushroom": [],
    "king oyster mushroom": [],
    "hearts of palm": [],
    "jackfruit": [],
    "seaweed": [],
    "nori": [],
    "kombu": [],
    "wakame": [],

    # added: fruit
    "strawberry": [],
    "blueberry": [],
    "raspberry": [],
    "blackberry": [],
    "cranberry": [],
    "blackcurrant": [],
    "cherry": [],
    "peach": [],
    "pear": [],
    "plum": [],
    "apricot": [],
    "nectarine": [],
    "grape": [],
    "melon": [],
    "watermelon": [],
    "cantaloupe": [],
    "kiwi": [],
    "papaya": [],
    "pomegranate": [],
    "fig": [],
    "date": [],
    "grapefruit": [],
    "tangerine": [],
    "clementine": [],
    "mandarin": [],
    "passion fruit": [],
    "lychee": [],
    "rhubarb": [],
    "persimmon": [],
    "guava": [],
    "applesauce": [],
    "dried mango": [],

    # added: herbs, spices, flavourings
    "sage": [],
    "tarragon": [],
    "marjoram": [],
    "lemongrass": [],
    "curry leaf": [],
    "saffron": [],
    "cardamom": [],
    "clove": [],
    "star anise": [],
    "anise": [],
    "caraway": [],
    "fenugreek": [],
    "allspice": [],
    "garam masala": [],
    "chili powder": [],
    "italian seasoning": [],
    "mixed herb": [],
    "sumac": [],
    "ras el hanout": [],
    "five spice": [],
    "cacao": [],
    "cocoa": [],
    "mixed spice": [],
    "smoked paprika": [],
    "mace": [],
    "juniper": [],
    "lavender": [],
    "rose water": [],
    "orange blossom water": [],
    "vanilla paste": [],
    "salt flake": [],
    "sea salt": [],
    "msg": [],

    # added: oils, baking and pantry
    "oil": [],
    "rapeseed oil": [],
    "cooking spray": [],
    "vegetable shortening": [],
    "bicarbonate of soda": [],
    "cornflour": [],
    "agar agar": [],
    "aquafaba meringue": [],
    "mushroom jerky": [],
    "vegetable suet": [],
    "pectin": [],
    "nutritional yeast": [],
    "pea protein": [],
    "jam": [],
    "marmalade": [],
    "hot sauce": [],
    "coffee": [],
    "tea": [],
    "vodka": [],
    "rum": [],
    "gin": [],
    "tequila": [],
    "sparkling water": [],
    "grape juice": [],
}

# Ingredient -> (substitute name, note). Only ingredients that can be flagged
# need one. Where several ingredients share the same real swap (all the pasta
# shapes, all the named cheeses), they point at the same Substitute row.
INGREDIENT_SUBSTITUTES = {
    "flour": ("gluten-free flour blend", "Use a 1:1 gluten-free blend for most baking recipes."),
    "wheat flour": ("gluten-free flour blend", "Use a 1:1 gluten-free blend for most baking recipes."),
    "plain flour": ("gluten-free flour blend", "Use a 1:1 gluten-free blend for most baking recipes."),
    "self raising flour": ("gluten-free self-raising flour blend", "Use a certified gluten-free self-raising blend 1:1."),
    "bread": ("gluten-free bread", "Use a certified gluten-free loaf or wrap."),
    "breadcrumbs": ("gluten-free breadcrumbs", "Use a certified gluten-free breadcrumb or crushed gluten-free crackers."),
    "panko": ("gluten-free breadcrumbs", "Use a certified gluten-free breadcrumb or crushed gluten-free crackers."),
    "pasta": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "spaghetti": ("gluten-free spaghetti", "Use a rice or corn-based gluten-free spaghetti 1:1."),
    "penne": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "macaroni": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "fusilli": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "linguine": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "tagliatelle": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "lasagne": ("gluten-free lasagne sheets", "Use rice or corn-based gluten-free sheets 1:1."),
    "lasagna": ("gluten-free lasagne sheets", "Use rice or corn-based gluten-free sheets 1:1."),
    "noodles": ("rice noodles", "Substitute 1:1 in most stir-fries and soups."),
    "egg noodles": ("rice noodles", "Substitute 1:1; also removes the egg content."),
    "couscous": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "bulgur": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "barley": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "rye": ("gluten-free flour blend", "Use a 1:1 gluten-free blend for baking."),
    "pastry": ("gluten-free pastry", "Use a certified gluten-free pastry or pie crust."),
    "puff pastry": ("gluten-free puff pastry", "Use a certified gluten-free puff pastry."),
    "pie crust": ("gluten-free pie crust", "Use a certified gluten-free pie crust."),
    "tortilla": ("corn tortilla", "Use a corn tortilla in place of a wheat one."),
    "pita": ("gluten-free flatbread", "Use a certified gluten-free flatbread or wrap."),
    "bun": ("gluten-free bun", "Use a certified gluten-free bun or lettuce wrap."),
    "baguette": ("gluten-free bread", "Use a certified gluten-free loaf."),
    "cracker": ("gluten-free crackers", "Use a certified gluten-free cracker."),
    "soy sauce": ("coconut aminos", "Substitute 1:1; slightly sweeter and lower sodium."),
    "worcestershire sauce": ("vegan worcestershire sauce", "Use a fish-free worcestershire-style sauce 1:1."),
    "egg": ("flax egg", "1 tbsp ground flaxseed + 3 tbsp water, rested 5 minutes, replaces 1 egg."),
    "quail egg": ("flax egg", "1 tbsp ground flaxseed + 3 tbsp water, rested 5 minutes, replaces 1 egg."),
    "mayonnaise": ("egg-free mayonnaise", "Use a store-bought vegan mayonnaise 1:1."),
    "meringue": ("aquafaba meringue", "Whipped chickpea brine (aquafaba) whips up similarly to egg whites."),
    "butter": ("vegan margarine", "Use a plant-based margarine or coconut oil in equal amounts."),
    "milk": ("oat milk", "Substitute 1:1 for dairy milk in most recipes."),
    "buttermilk": ("oat milk + lemon juice", "1 cup oat milk + 1 tbsp lemon juice, rested 5 minutes."),
    "cheese": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "cheddar": ("dairy-free cheddar", "Use a plant-based cheddar-style alternative."),
    "mozzarella": ("dairy-free mozzarella", "Use a plant-based mozzarella alternative; melting behavior may differ."),
    "parmesan": ("nutritional yeast", "Use to taste for a similar savory, cheesy flavor."),
    "pecorino": ("nutritional yeast", "Use to taste for a similar savory, cheesy flavor."),
    "feta": ("dairy-free feta", "Use a plant-based feta-style alternative, often made from tofu."),
    "ricotta": ("blended firm tofu", "Blended with lemon juice and salt for a similar texture."),
    "mascarpone": ("cashew cream", "Blended soaked cashews for a similar rich texture."),
    "brie": ("dairy-free soft cheese", "Use a plant-based soft cheese alternative."),
    "gouda": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "halloumi": ("firm tofu", "Sliced and pan-seared for a similar salty, chewy texture."),
    "cream": ("coconut cream", "Substitute 1:1 in most sauces and desserts."),
    "cream cheese": ("dairy-free cream cheese", "Use a plant-based cream cheese alternative 1:1."),
    "heavy cream": ("coconut cream", "Substitute 1:1 in most sauces and desserts."),
    "whipping cream": ("coconut cream", "Chilled and whipped, substitutes 1:1."),
    "sour cream": ("dairy-free sour cream", "Use a plant-based sour cream alternative 1:1."),
    "yogurt": ("coconut yogurt", "Substitute 1:1 in most recipes."),
    "yoghurt": ("coconut yogurt", "Substitute 1:1 in most recipes."),
    "condensed milk": ("dairy-free condensed milk", "Use a coconut-based condensed milk alternative 1:1."),
    "evaporated milk": ("oat milk", "Substitute 1:1; simmer briefly to thicken if needed."),
    "milk chocolate": ("dairy-free dark chocolate", "Use a dairy-free dark chocolate 1:1."),
    "custard": ("egg-free dairy-free custard", "Use an oat or coconut milk custard thickened with cornflour and a pinch of turmeric; no eggs needed."),
    "ice cream": ("dairy-free ice cream", "Use a coconut or oat milk based ice cream alternative."),
    "honey": ("maple syrup", "Use in equal amounts; slightly thinner consistency."),
    "chicken": ("seitan", "Sliced or cubed and seasoned similarly, pan-seared or baked."),
    "beef": ("seitan", "Use in equal amounts; adjust cooking time as it needs less."),
    "ground beef": ("plant-based mince", "Use a store-bought plant-based mince 1:1."),
    "mince": ("plant-based mince", "Use a store-bought plant-based mince 1:1."),
    "pork": ("jackfruit", "Shredded and seasoned similarly for a comparable texture."),
    "bacon": ("smoked tempeh", "Sliced thin and pan-fried for a similar smoky, salty bite."),
    "pancetta": ("smoked tempeh", "Sliced thin and pan-fried for a similar smoky, salty bite."),
    "prosciutto": ("smoked tempeh", "Thinly sliced for a similar salty, savory note."),
    "guanciale": ("smoked tempeh", "Sliced thin and pan-fried for a similar smoky, salty bite."),
    "chorizo": ("spiced plant-based sausage", "Use a store-bought spiced plant-based sausage."),
    "sausage": ("plant-based sausage", "Use a store-bought plant-based sausage 1:1."),
    "salami": ("plant-based salami", "Use a store-bought plant-based deli slice."),
    "ham": ("smoked tempeh", "Sliced thin for a similar smoky, savory note."),
    "turkey": ("seitan", "Sliced or cubed and seasoned similarly, pan-seared or baked."),
    "duck": ("seitan", "Seasoned similarly and pan-seared or baked."),
    "lamb": ("jackfruit", "Shredded and seasoned similarly for a comparable texture."),
    "veal": ("seitan", "Sliced or cubed and seasoned similarly, pan-seared or baked."),
    "venison": ("seitan", "Seasoned similarly and pan-seared or baked."),
    "chicken stock": ("vegetable stock", "Substitute 1:1 in soups and sauces."),
    "beef stock": ("vegetable stock", "Substitute 1:1 in soups and sauces."),
    "chicken broth": ("vegetable broth", "Substitute 1:1 in soups and sauces."),
    "beef broth": ("vegetable broth", "Substitute 1:1 in soups and sauces."),
    "gelatin": ("agar agar", "Use about half the amount of agar agar powder as a plant-based setting agent."),
    "salmon": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "tuna": ("mashed chickpeas", "Mashed with the same seasonings for a similar texture in salads and sandwiches."),
    "cod": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "haddock": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "halibut": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "mackerel": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "sardine": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "trout": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "anchovy": ("capers", "Use a small amount for a similar salty, briny note."),
    "sea bass": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "fish sauce": ("soy sauce", "Use a small amount as a savory, salty substitute; flavor profile differs."),
    "fish stock": ("vegetable stock", "Substitute 1:1 in soups and sauces."),
    "shrimp": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "prawn": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "crab": ("hearts of palm", "Shredded for a similar texture in salads and cakes."),
    "lobster": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "mussels": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "clams": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "oyster": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "scallop": ("king oyster mushroom", "Sliced into rounds and pan-seared for a similar texture."),
    "squid": ("king oyster mushroom", "Sliced into rings and pan-seared for a similar texture."),
    "calamari": ("king oyster mushroom", "Sliced into rings and pan-seared for a similar texture."),
    "almond": ("sunflower seeds", "Use in equal amounts for baking or snacking."),
    "walnut": ("sunflower seeds", "Use in equal amounts for baking or snacking."),
    "cashew": ("sunflower seeds", "Use in equal amounts for baking or sauces."),
    "hazelnut": ("sunflower seeds", "Use in equal amounts for baking or snacking."),
    "pistachio": ("sunflower seeds", "Use in equal amounts for baking or snacking."),
    "pecan": ("sunflower seeds", "Use in equal amounts for baking or snacking."),
    "macadamia": ("sunflower seeds", "Use in equal amounts for baking or snacking."),
    "brazil nut": ("sunflower seeds", "Use in equal amounts for baking or snacking."),
    "pine nut": ("sunflower seeds", "Use in equal amounts in pesto or baking."),
    "peanut": ("sunflower seeds", "Use in equal amounts for snacking or toppings."),
    "peanut butter": ("sunflower seed butter", "Use in equal amounts for spreads and baking."),
    "sesame oil": ("sunflower oil", "Neutral substitute; won't replicate the toasted flavor."),
    "sesame seeds": ("poppy seeds", "Use in equal amounts as a topping."),
    "tahini": ("sunflower seed butter", "Use in equal amounts in dressings and sauces."),
    "tofu": ("chickpeas", "Use cooked chickpeas for a similar protein source in stir-fries and salads."),
    "soy milk": ("oat milk", "Substitute 1:1 for soy milk in most recipes."),
    "tempeh": ("mushroom", "Sliced and pan-seared for a similar texture."),
    "edamame": ("green peas", "Use in equal amounts in salads and stir-fries."),
    "miso": ("chickpea miso", "Use a soy-free chickpea-based miso 1:1."),
    "wine": ("grape juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "white wine": ("white grape juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "red wine": ("red grape juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "dried apricot": ("dried mango", "Use a sulphite-free dried fruit in equal amounts."),
    "raisins": ("fresh grapes", "Use a sulphite-free dried fruit, or fresh grapes, in equal amounts."),

    # added with the larger dictionary
    "wheat": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "spelt": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "kamut": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "farro": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "freekeh": ("quinoa", "Use in equal amounts as a gluten-free grain substitute."),
    "seitan": ("jackfruit", "Shredded and seasoned similarly for a comparable texture."),
    "malt vinegar": ("apple cider vinegar", "Substitute 1:1 for a similar tang."),
    "beer": ("gluten-free beer", "Use a certified gluten-free beer or cider 1:1."),
    "gnocchi": ("gluten-free gnocchi", "Use a certified gluten-free gnocchi."),
    "orzo": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "rigatoni": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "farfalle": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "fettuccine": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "pappardelle": ("gluten-free pasta", "Use rice, corn, or legume-based pasta 1:1."),
    "ravioli": ("gluten-free ravioli", "Use a certified gluten-free filled pasta."),
    "tortellini": ("gluten-free tortellini", "Use a certified gluten-free filled pasta."),
    "cannelloni": ("gluten-free lasagne sheets", "Use rice or corn-based gluten-free sheets 1:1."),
    "ramen": ("rice noodles", "Substitute 1:1 in most stir-fries and soups."),
    "udon": ("rice noodles", "Substitute 1:1 in most stir-fries and soups."),
    "dough": ("gluten-free dough", "Use a gluten-free dough mix or ready-made gluten-free dough."),
    "pizza dough": ("gluten-free pizza base", "Use a ready-made gluten-free pizza base or dough mix."),
    "pizza base": ("gluten-free pizza base", "Use a ready-made gluten-free pizza base or dough mix."),
    "bagel": ("gluten-free bagel", "Use a certified gluten-free bagel."),
    "naan": ("gluten-free flatbread", "Use a certified gluten-free flatbread or wrap."),
    "chapati": ("gluten-free flatbread", "Use a certified gluten-free flatbread or wrap."),
    "roti": ("gluten-free flatbread", "Use a certified gluten-free flatbread or wrap."),
    "flatbread": ("gluten-free flatbread", "Use a certified gluten-free flatbread or wrap."),
    "ciabatta": ("gluten-free bread", "Use a certified gluten-free loaf or wrap."),
    "sourdough": ("gluten-free bread", "Use a certified gluten-free loaf or wrap."),
    "pretzel": ("gluten-free pretzels", "Use certified gluten-free pretzels."),
    "biscuit": ("gluten-free biscuit", "Use a certified gluten-free biscuit."),
    "crouton": ("gluten-free croutons", "Use certified gluten-free croutons or toasted gluten-free bread."),
    "breadstick": ("gluten-free breadsticks", "Use certified gluten-free breadsticks."),
    "english muffin": ("gluten-free muffin", "Use a certified gluten-free muffin or bread round."),
    "filo": ("gluten-free pastry", "Use a certified gluten-free pastry or pie crust."),
    "phyllo": ("gluten-free pastry", "Use a certified gluten-free pastry or pie crust."),
    "wonton wrapper": ("rice paper", "Use rice paper wrappers; soften them in water first."),
    "dumpling wrapper": ("rice paper", "Use rice paper wrappers; soften them in water first."),
    "croissant": ("gluten-free vegan croissant", "Look for a certified gluten-free, dairy-free pastry."),
    "brioche": ("gluten-free vegan bread", "Look for a certified gluten-free, egg-free, dairy-free sweet bread."),
    "almond flour": ("sunflower seed flour", "Grind sunflower seeds finely and use 1:1."),
    "eggnog": ("plant-based nog", "Use a store-bought plant-based nog."),
    "mayo": ("egg-free mayonnaise", "Use a store-bought vegan mayonnaise 1:1."),
    "aioli": ("egg-free mayonnaise", "Use a vegan mayonnaise with crushed garlic."),
    "hollandaise": ("vegan hollandaise", "Use a store-bought vegan hollandaise, or whisk vegan margarine, lemon juice and a pinch of turmeric."),
    "marshmallow": ("vegan marshmallows", "Use a gelatin-free marshmallow 1:1."),
    "whey": ("pea protein", "Use a plant-based protein powder."),
    "casein": ("pea protein", "Use a plant-based protein powder."),
    "ghee": ("coconut oil", "Substitute 1:1 for a similar high-heat fat."),
    "paneer": ("firm tofu", "Pressed and cubed for a similar firm, mild texture."),
    "labneh": ("coconut yogurt", "Strain through a cloth overnight for a thicker, labneh-like texture."),
    "skyr": ("coconut yogurt", "Substitute 1:1 in most recipes."),
    "kefir": ("coconut yogurt", "Thin with a little plant milk to a drinkable consistency."),
    "quark": ("coconut yogurt", "Strain through a cloth for a thicker texture."),
    "creme fraiche": ("dairy-free sour cream", "Use a plant-based sour cream alternative 1:1."),
    "half and half": ("oat milk", "Substitute 1:1; use oat cream for a richer result."),
    "dulce de leche": ("coconut caramel", "Use a coconut-milk based caramel spread."),
    "gelato": ("dairy-free ice cream", "Use a coconut or oat milk based ice cream alternative."),
    "buttercream": ("vegan buttercream", "Beat vegan margarine with icing sugar."),
    "white chocolate": ("dairy-free white chocolate", "Use a dairy-free white chocolate 1:1."),
    "gorgonzola": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "stilton": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "camembert": ("dairy-free soft cheese", "Use a plant-based soft cheese alternative."),
    "emmental": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "gruyere": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "provolone": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "manchego": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "asiago": ("nutritional yeast", "Use to taste for a similar savory, cheesy flavor."),
    "romano": ("nutritional yeast", "Use to taste for a similar savory, cheesy flavor."),
    "fontina": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "cotija": ("dairy-free feta", "Use a plant-based feta-style alternative, crumbled."),
    "queso fresco": ("dairy-free feta", "Use a plant-based feta-style alternative, crumbled."),
    "burrata": ("dairy-free mozzarella", "Use a plant-based mozzarella alternative; melting behavior may differ."),
    "taleggio": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "monterey jack": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "pepper jack": ("dairy-free cheese", "Use a plant-based cheese alternative; melting behavior may differ."),
    "almond milk": ("oat milk", "Substitute 1:1 in most recipes."),
    "cashew milk": ("oat milk", "Substitute 1:1 in most recipes."),
    "soya milk": ("oat milk", "Substitute 1:1 for soy milk in most recipes."),
    "soy yogurt": ("coconut yogurt", "Substitute 1:1 in most recipes."),
    "meat": ("plant-based mince", "Use a store-bought plant-based mince 1:1."),
    "steak": ("portobello mushroom", "Thick slices, marinated and grilled, for a meaty bite."),
    "ribeye": ("portobello mushroom", "Thick slices, marinated and grilled, for a meaty bite."),
    "sirloin": ("portobello mushroom", "Thick slices, marinated and grilled, for a meaty bite."),
    "brisket": ("jackfruit", "Shredded and slow-cooked with smoky seasoning."),
    "short rib": ("jackfruit", "Shredded and slow-cooked with similar seasoning."),
    "oxtail": ("jackfruit", "Shredded and slow-cooked with similar seasoning."),
    "mutton": ("jackfruit", "Shredded and seasoned similarly for a comparable texture."),
    "goat": ("jackfruit", "Shredded and seasoned similarly for a comparable texture."),
    "rabbit": ("seitan", "Seasoned similarly and pan-seared or baked."),
    "bison": ("plant-based mince", "Use a store-bought plant-based mince 1:1."),
    "liver": ("mushroom", "Sliced and pan-seared for a similar earthy flavor."),
    "meatball": ("plant-based meatballs", "Use store-bought plant-based meatballs 1:1."),
    "hot dog": ("plant-based sausage", "Use a store-bought plant-based sausage 1:1."),
    "frankfurter": ("plant-based sausage", "Use a store-bought plant-based sausage 1:1."),
    "bratwurst": ("plant-based sausage", "Use a store-bought plant-based sausage 1:1."),
    "pepperoni": ("plant-based pepperoni", "Use a store-bought plant-based pepperoni."),
    "mortadella": ("plant-based deli slices", "Use store-bought plant-based deli slices."),
    "jerky": ("mushroom jerky", "Use a store-bought mushroom or soy-free plant-based jerky."),
    "lard": ("vegetable shortening", "Substitute 1:1 for baking and frying."),
    "suet": ("vegetable suet", "Use a vegetable suet 1:1."),
    "tallow": ("vegetable shortening", "Substitute 1:1 for frying."),
    "bone broth": ("vegetable broth", "Substitute 1:1 in soups and sauces."),
    "gelatine": ("agar agar", "Use about half the amount of agar agar powder as a plant-based setting agent."),
    "fish": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "tilapia": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "snapper": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "swordfish": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "mahi mahi": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "pollock": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "herring": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "eel": ("glazed aubergine", "Grilled and brushed with the same glaze for a similar texture."),
    "caviar": ("seaweed pearls", "Use seaweed-based vegan caviar."),
    "roe": ("seaweed pearls", "Use seaweed-based vegan caviar."),
    "bonito": ("kombu", "Use kombu seaweed for a similar umami depth."),
    "dashi": ("kombu dashi", "Use a kombu or shiitake dashi."),
    "surimi": ("hearts of palm", "Shredded for a similar texture in salads and cakes."),
    "shellfish": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "crayfish": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "langoustine": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "cuttlefish": ("king oyster mushroom", "Sliced into rings and pan-seared for a similar texture."),
    "octopus": ("king oyster mushroom", "Sliced and pan-seared for a similar texture."),
    "seafood": ("marinated tofu", "Firm tofu marinated in similar seasonings, pan-seared or baked."),
    "chestnut": ("sunflower seeds", "Use in equal amounts for baking or roasting."),
    "almond butter": ("sunflower seed butter", "Use in equal amounts for spreads and baking."),
    "cashew butter": ("sunflower seed butter", "Use in equal amounts for spreads and baking."),
    "nutella": ("sunflower seed chocolate spread", "Use a nut-free chocolate spread; check the label if you also avoid dairy."),
    "pesto": ("sunflower seed pesto", "Blend basil, sunflower seeds, olive oil, garlic and nutritional yeast."),
    "groundnut": ("sunflower seeds", "Use in equal amounts for snacking or toppings."),
    "sesame": ("poppy seeds", "Use in equal amounts as a topping."),
    "hummus": ("sesame-free hummus", "Blend chickpeas with olive oil, lemon juice and garlic; skip the tahini."),
    "za'atar": ("sesame-free za'atar", "Mix dried thyme, sumac and salt."),
    "soya": ("chickpeas", "Use cooked chickpeas for a similar protein source."),
    "soy bean": ("chickpeas", "Use cooked chickpeas for a similar protein source."),
    "soybean": ("chickpeas", "Use cooked chickpeas for a similar protein source."),
    "soy flour": ("chickpea flour", "Substitute 1:1 in baking."),
    "soy protein": ("pea protein", "Use a plant-based protein powder."),
    "bean curd": ("chickpeas", "Use cooked chickpeas for a similar protein source."),
    "sultana": ("fresh grapes", "Use fresh grapes, or a sulphite-free dried fruit, in equal amounts."),
    "sherry": ("grape juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "marsala": ("grape juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "vermouth": ("white grape juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "champagne": ("sparkling water", "Use sparkling water with a squeeze of lemon juice."),
    "prosecco": ("sparkling water", "Use sparkling water with a squeeze of lemon juice."),
    "brandy": ("apple juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "cognac": ("apple juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "port wine": ("grape juice", "Use in equal amounts; reduce added sugar elsewhere in the recipe."),
    "rice wine": ("rice vinegar", "Use half the amount of rice vinegar, diluted with a little water."),
    "honeycomb": ("maple syrup", "Use in equal amounts; texture will differ."),
}
